language: node_js
node_js:
- 11
sudo: true
env:
  global:
  - secure: Xu+qIHo8JHLBdO8hHK1zz5XZMAfQjdcrPCQiQJD/Siz8o9oxg5R1d2G4h074ec3MKawUKYicHoZ0lZdz9ZUw6P61d4MGmRGS2YHcE7Kz7dCZKfy/8aFpVecngoW1L+7JFNJaJVO0mfc5Sk+HJlZQQygm2ZIYOkvHk1KvYRCoDPRm/jnO+Le2qlLyLmRYs/7FS1+ANCIzFO0IZC80/L4C36Tbazp5zy7eswzOjozxO6iSPtjwFpcn/tPW2MD1R5VZYENilunNwF6x8Ke/xG43K4k+WcK8SqeGHA/wkhHaw/UNxdLfBdNiJstQZO9p950ZWGydiBrSKYXDAYgWjT24Ua0VDgTpaC8s3UFg2TKtTS573ujSGxCPdcQp4My6ws4h4SLvIbXdkT9MvYV5KvYnYMfE90pBNL0iwRvfpwY7h2PrH7mVd07GfwPIX0K1br6DskrvI1lyIX8Mpwol+SdBa65ozOaty1enkLuX8pwAyJnTl/+EwU2gHYOwjrYsOTE5uOdE4tnrL1ASryHpI/v2+AAPv1ht91ExDSkd+hA5OKO2AZO+6D7IERVt5xo9LSGvWenxB4plrZ5kAPcUh/CS6pFZTSD++jNIK1aQ0L4URU4ng3JOG+4uxCc6wCP3SG3DlOwNCyXeZKNOSAOCPdI7bO0H+/tDPWiN+/EIVs7GVW8=
  - secure: gLf+FLztWd0N31UpRiodMTKeUNqZAmItO+HB7verH7VOe1Yk+7gaZ2goQkUaVHlFHqyhBtqiK58hvMlzkyvtkN71TTlpVXKFxVzQyGKPONAH+kxo3vYTp9YztsNTvFUaPw9SxoTx+qvU7XD5y4AZy72SmWxqcwJTzwOxnVu3vD+h+QYvr8DEPlBXkWj0hP0Y3iQbulTXaG6NMrucDfnOkCyNx4PJJfWZORrpqygmZSnJR7IyX9mKrNoieA1VTNL9xkE1wsZbm8sydWT1kpvr6/3dIWJX0JjzcloYtFdvV+8lISksB8mqgR6h1D/KOvE86DW3d0Uc+tEfiD+E7pnQ/THFm6hAAnsQMsJ1D0cY1GJKHogR/Bw5gt68DLF13WITZIkaO1F1bx8BA6irRDK7tQYd3xgXFy159faC/EwwY7W45c1LrVvJFpw2VKMfo3f65b8H8uup5D/50DTCK509JDzpwUopwXLo4AbeRm6STLar/hbNTBOkKHW79KscGLUlwo99zqiL3i7q6uPmgvdPy6n2sVtdv40483qXOZGYhmARsrTtCcJuVcjXQr3CxJP0X7bwZibQFNPvZLA1TeJn+KyjAN0tDXRPOpePiSbhVkePx2x7TtHduIzHQjsnLm4lrop9wc/IF/JlmL69ol+zJEkACdaD9TQKozoX/aIB3Gs=
  - secure: oyQbwc11h/eqqepisim31XQys+ohKUocQlhTEw9PmJPzOORRR+wRTXey381pKQr2hy1X1u44znWbpSZZpZia08WD6O88izuf6KZq2cs/N76kXFVDEFE1fJ4/1djERtO6semjNByo3SJgJ2h/cA1sWBIS89GWVHf/jTgWjPkNzYwksIcpqimL/iPjr/zkiDYAjyO0753B+rnF/r15Otf3nnMf2b0FaFTZ/tp81agRGTl5TIW8gCMFbGeVMEfotW9ni23nxAIRp6jz8n8ZYjPZDlbX4H9lOlFjfpuFK2krTqAPcSm9x4xWdjNofy28QjDy6TwFPkmKSRh5vuqtLJwmaAftkqFXnPT7z1cFM0FUcdOBuOLlni+ISFsdX64GLc1dOKJmIjjOSVAj13qLYJLBAlGjLNSGOJ0dddyzn0084MhHVjPOmaIHbNok0v/Te0/NoNg2fseOc+jHEbQpLUprwurHoExvvSFqznWbOLXc5xUs50cnT5wvDBfsnDLB6d/dFvK8Dg5HFWF01W/O5ycVUOyKzDf5Xb4MqUHx49x2fUgYqmCK+NvvDmoPqWh6dRryU6eZaORkuxYm0MzJSS88rlTjqLOCaUHLx85eEy7HdfUb9TTt7K2tG3Pvo9Jw/L1IeKCPJC440z/G2Drm5DQgj6AIJ4rYX64kbuybndUKvZ8=

jobs:
  include:
  - stage: test
    if: branch = master
    before_script: curl https://rclone.org/install.sh | sudo bash
    script:
    - npm run test
    - npm run build
    - rclone copy dist :s3://payone/dev/ --s3-access-key-id=$S3_ACCESS_KEY --s3-endpoint=$S3_HOST
      --s3-secret-access-key=$S3_SECRET_KEY

after_success: 

notifications:
  email: false
  slack:
    secure: AEx0melqLH4YofPkQj/Wc81TH1zM9vUT7N9Zg8C20BG+xrodBnp9i9fO2vUrtz0FErBKakq/0PuDYlH/4qLKAmDMuJ7LDB0OWwM5G/wSUw6atHtNMzprDG/JbQOxjDr0IGvMltoAprc6NRo6dRzLwVvTtLFT0Ot3fbcOBhhph8pIGPGw3aSKwcYZQ0cAJboBRu2qiqUWXfKY5UIvlIgBFkphZdnw2fotuIbueConyeBz86yde2ulFdfw8zU3tNOQLLpAmz6RnR6TRenXHGdv8km8HYTDuPiyli56TXj2hWYTCFYV7cJFcvH63F55xp1h98MTlmxc5uBMz+hWN1embMeGTq+cUnI/TjjBklOPsRxMB9GRbAP2q6s4rzvtaklml5a6OOEwb0Yw4NeUXfqpL/jcOzzru42TaLQcNGgxdkxJLtK1K933H7Q2VygnDU9lfWCbQzSZMuvambRmgZCs4/Mb1YROH20aM6v1GgR9QpjI/2SbP25R+j8Dyltc/zvPnATCeIpHvZGgsiNH1camPD3QKqsHyrmm1pA79UXhw4Oobv7erfbTFYop9+FuikASmN9ZTrqkuzd3nW4nzQGCKAMU5esCiCx9mwwz3HBAaDnvEQIGxhdpXJHKgV3hNH466JKQ8U4T7rLGHp4GzT/8lMG69XwU+nFA6TBZO/M7V98=
